In [619]:
import numpy as np
import pandas as pd

In [620]:
stack_skills = pd.read_csv('DB/stackoverflow_skills.csv')

In [621]:
bsj_skills = pd.read_csv('DB/bsj_skills.csv')

In [622]:
frames = [stack_skills, bsj_skills]

In [623]:
skills = pd.concat(frames)

In [624]:
skills.head()

   job_id   skill
0     553       r
1     553  python
2     553     sql
3     554  python
4     554     sql

In [625]:
bsj_jobs = pd.read_csv('DB/bsj_jobs.csv')
bsj_jobs.head()

,ID,company_name,jobtitle,description,date,source
0,1,Fatmap,Mobile Engineer for Outdoor Adventure Sports,Role & Responsibility: \n\nYou’ll be building ...,2017-10-02,Berlin Startup Jobs
1,2,AI Engine,Machine Learning,AI Engine is developing innovative machine lea...,2017-10-02,Berlin Startup Jobs
2,3,November,Senior Full Stack PHP Developer (f/m),Your mission:\n\nDevelopment of a scalable sof...,2017-10-02,Berlin Startup Jobs
3,4,Wayfair,Jr. Manager SEO UK (Onpage) (m/f),Your tasks:\n\nKeyword research and competitor...,2017-10-02,Berlin Startup Jobs
4,5,CrossEngage,Data Scientist,About CrossEngage\nCrossEngage is a cloud-base...,2017-10-02,Berlin Startup Jobs

In [626]:
stack_jobs = pd.read_csv('DB/stackoverflow_jobs.csv')
stack_jobs.head()

,ID,jobtitle,description,company_name,source,date
0,1535,"Senior PHP Engineer, Marketplace - Turn trips ...",Our Marketplace department is looking for a Se...,GetYourGuide AG,Stackoverflow,2017-11-26
1,1536,Senior Frontend Engineer (m/f) at Bonial Inter...,What the team lead says about the team:The CDP...,Bonial International GmbH,Stackoverflow,2017-11-26
2,1537,Senior Frontend Engineer (f/m) at Delivery Her...,Delivery Hero is building the next generation ...,Delivery Hero AG,Stackoverflow,2017-11-26
3,1538,DevOps Engineer (m/f) at CeleraOne GmbH (Berli...,StellenbeschreibungDevelop the future of journ...,CeleraOne GmbH,Stackoverflow,2017-11-26
4,1539,Java Developer wanted for leading e-hailing ap...,As of now we are looking to recruit a highly m...,mytaxi (Intelligent Apps GmbH),Stackoverflow,2017-11-26

In [627]:
frames2 = [bsj_jobs, stack_jobs]

In [628]:
jobs = pd.concat(frames2)

In [629]:
jobs.head(10)

,ID,company_name,date,description,jobtitle,source
0,1,Fatmap,2017-10-02,Role & Responsibility: \n\nYou’ll be building ...,Mobile Engineer for Outdoor Adventure Sports,Berlin Startup Jobs
1,2,AI Engine,2017-10-02,AI Engine is developing innovative machine lea...,Machine Learning,Berlin Startup Jobs
2,3,November,2017-10-02,Your mission:\n\nDevelopment of a scalable sof...,Senior Full Stack PHP Developer (f/m),Berlin Startup Jobs
3,4,Wayfair,2017-10-02,Your tasks:\n\nKeyword research and competitor...,Jr. Manager SEO UK (Onpage) (m/f),Berlin Startup Jobs
4,5,CrossEngage,2017-10-02,About CrossEngage\nCrossEngage is a cloud-base...,Data Scientist,Berlin Startup Jobs
5,6,Ruum,2017-10-02,If you’re passionate about learning new techno...,Full Stack Developer,Berlin Startup Jobs
6,7,Auto1.com,2017-10-02,What you will do:\n\nFull lifecycle engineerin...,Senior Java Developer,Berlin Startup Jobs
7,8,Elinvar,2017-10-02,Elinvar offers an integrated solution for asse...,Junior DevOps Engineer (m/f),Berlin Startup Jobs
8,9,AI Engine,2017-10-02,AI Engine is developing innovative machine lea...,Java or Python Developer,Berlin Startup Jobs
9,10,PubNative,2017-10-02,Your Responsibilities:\n\nUncover new opportun...,Data Scientist (m/f),Berlin Startup Jobs

In [630]:
jobs.to_csv('merged_jobs.csv', sep=',')

In [631]:
skills.to_csv('merged_skills.csv', sep=',')

In [632]:
merged_skills = pd.read_csv('merged_skills.csv', index_col=0)
merged_skills.head()

   job_id   skill
0     553       r
1     553  python
2     553     sql
3     554  python
4     554     sql

In [633]:
merged_skills.keys()

Index(['job_id', 'skill'], dtype='object')

In [634]:
from sklearn.cluster import KMeans

In [635]:
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from sklearn.feature_extraction import text

In [636]:
import nltk.stem
global english_stemmer 
english_stemmer = nltk.stem.SnowballStemmer('english')
class StemmedCountVectorizer(CountVectorizer):
    def build_analyzer(self):
        analyzer = super(CountVectorizer, self).build_analyzer()
        return lambda doc: (english_stemmer.stem(w) for w in analyzer(doc))

In [637]:
stop_words = ['and','&']
vectorizer = StemmedCountVectorizer(min_df=15, max_df=0.5, stop_words = stop_words)
vectorized = vectorizer.fit_transform(merged_skills['skill'].values.astype('U'))

In [638]:
num_clusters = 90
km = KMeans(n_clusters = num_clusters, init = 'k-means++', n_init = 1,verbose=1)
clustered = km.fit(vectorized)
predict = km.predict(vectorized)

Initialization complete
Iteration  0, inertia 49.000
Iteration  1, inertia 45.353
Converged at iteration 1: center shift 0.000000e+00 within tolerance 9.122709e-07

In [639]:
vectorizer.get_feature_names()

['agil',
 'android',
 'angular',
 'angularj',
 'ansibl',
 'apach',
 'api',
 'aw',
 'azur',
 'cassandra',
 'chef',
 'ci',
 'cloud',
 'continu',
 'css',
 'css3',
 'django',
 'docker',
 'elasticsearch',
 'es6',
 'git',
 'go',
 'googl',
 'gulp',
 'hadoop',
 'html',
 'html5',
 'http',
 'io',
 'java',
 'javascript',
 'jenkin',
 'jira',
 'jqueri',
 'js',
 'json',
 'kafka',
 'kanban',
 'kubernet',
 'laravel',
 'learn',
 'less',
 'linux',
 'machin',
 'mongodb',
 'mysql',
 'nan',
 'nativ',
 'nginx',
 'node',
 'nodej',
 'nosql',
 'object',
 'on',
 'php',
 'postgresql',
 'puppet',
 'python',
 'rabbitmq',
 'rail',
 'react',
 'reactj',
 'redi',
 'redux',
 'rest',
 'rubi',
 'sass',
 'scala',
 'scrum',
 'selenium',
 'spark',
 'spring',
 'sql',
 'swift',
 'sysadmin',
 'tdd',
 'test',
 'typescript',
 'ui',
 'unix',
 'vue',
 'webpack']

In [640]:
skills

      job_id                   skill
0        553                       r
1        553                  python
2        553                     sql
3        554                  python
4        554                     sql
5        554                       r
6        555                  python
7        555                  django
8        555                     aws
9        555                     sql
10       555                   scrum
11       556                   linux
12       556              postgresql
13       556                    ceph
14       556                  python
15       557  continuous-integration
16       557                      qa
17       557         automated-tests
18       557                     sql
19       557                  python
20       558                  python
21       558                     sql
22       558           deep-learning
23       559                    ruby
24       559                     sql
25       559                  python
26       560                  python
27       560                  django
28       560              postgresql
29       561                  python
...      ...                     ...
3489     485           SQL Injection
3490     485                    CSRF
3491     485            OWASP Top 10
3492     486                   Linux
3493     486                  Python
3494     486                React JS
3495     486            React Native
3496     486                 Android
3497     486                     iOS
3498     487                    Java
3499     487                     PHP
3500     487                    J2EE
3501     487                  Spring
3502     487                   Azure
3503     487                     AWS
3504     487                   MySQL
3505     487           ElasticSearch
3506     487                 MongoDB
3507     487            RESTful APIs
3508     487                Saltsack
3509     487                  Puppet
3510     487                    Chef
3511     487                  Docker
3512     487              Kubernetes
3513     488                     NaN
3514     489                      C#
3515     489              JavaScript
3516     489            Visual Basic
3517     489                     XML
3518     489                    Apex

[4745 rows x 2 columns]

In [641]:
len(predict)

4745

In [642]:
vectorized.shape

(4745, 82)

In [643]:
len(skills.skill)

4745

In [644]:
skills['cluster'] = predict

In [645]:
skills[skills['cluster'] == 10]

      job_id             skill  cluster
115      580               php       10
174      592               php       10
210      599               php       10
287      615               php       10
301      617               php       10
311      620               php       10
341      626               php       10
344      627               php       10
374      633               php       10
391      637               php       10
394      638               php       10
403      640               php       10
457      652               php       10
487      658               php       10
495      660               php       10
508      663               php       10
511      663      composer-php       10
517      665               php       10
538      670               php       10
609      686               php       10
671      700               php       10
710      710               php       10
788      727               php       10
918      757               php       10
950      763               php       10
11         3               PHP       10
182       31               PHP       10
329       47               PHP       10
548       83               PHP       10
577       86           php-fpm       10
...      ...               ...      ...
1857     258               PHP       10
1878     259               PHP       10
2075     290               PHP       10
2190     306               PHP       10
2240     317               PHP       10
2266     321               PHP       10
2267     322               PHP       10
2288     323               PHP       10
2362     332               PHP       10
2371     333               PHP       10
2384     336               PHP       10
2405     338               PHP       10
2489     352               PHP       10
2509     354               PHP       10
2580     365               PHP       10
2603     370               PHP       10
2661     380               PHP       10
2685     385               PHP       10
2765     393               PHP       10
2777     394               PHP       10
2780     395               PHP       10
2798     396               PHP       10
2938     413               PHP       10
2965     415   PHP Codeception       10
2970     416               PHP       10
3029     421               PHP       10
3378     473               PHP       10
3383     473       Phalcon PHP       10
3441     481               PHP       10
3499     487               PHP       10

[79 rows x 3 columns]

In [646]:
skills.sort_values('cluster').count()

job_id     4745
skill      4715
cluster    4745
dtype: int64

In [647]:
gg = skills.groupby('cluster')

In [648]:
import collections, re, operator
from collections import Counter
def BagofWords(textlist):
    bagsofwords = [ collections.Counter(re.findall(r'\w+', txt))
            for txt in textlist]
    words=Counter()
    for bbb in bagsofwords:
        for bb,v in bbb.items():  
            words[bb]+=v
    sorted_words = sorted(words.items(), key=operator.itemgetter(1),reverse=True)
    return sorted_words

In [649]:
from collections import defaultdict
d=defaultdict()
key=set(predict)
for k in key:
    d[k]=[]
for x,y in gg:
    d[x]+=list(y.skill.values)
    print (y.skill.values)

['javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' 'javascript' 'javascript' 'javascript' 'javascript'
 'javascript' ' JavaScript' ' Javascript' 'JavaScript' ' Javascript'
 'Javascript' ' JavaScript' ' JavaScript' 'Javascript' ' JavaScript'
 ' JavaScript ' 'Javascript' ' JavaScript' ' JavaScript' ' JavaScript'
 'JavaScript' ' Javascript' 'JavaScript' 'JavaScript' 'JavaScript'
 ' Javascript' 'JavaScript' 'Javascript' ' JavaScript' 'Javascript'
 ' Javascript' ' Javascript' ' JavaScript' ' Javascript' 'JavaScript'
 ' JavaScript' 'Javascript' ' Javascript' ' Javascript' ' Javascript'
 ' javascript' 'Javascript ES2015' ' CSS and JavaScript' 'JavaScript'
 ' JavaScript' ' Javascript' ' Javascript' ' JavaScript' ' JavaScript'
 ' Javascript' ' Javascript' 'JavaScript' ' JavaScript' ' Javascript'
 'Javascript' ' JavaScript' ' Javascript' ' JavaScript' ' JavaScript'
 ' JavaScript' 'Javascript' ' JavaScript' 'Javascript' ' Javascript'
 ' Javascript' ' Javascript' ' Javascript' 'JavaScript' ' JavaScript'
 'JavaScript' ' Javascript' ' JavaScript' ' JavaScript' ' JavaScript'
 'JavaScript' ' JavaScript' ' JavaScript' 'JavaScript (ES2015)'
 'Javascript' 'Javascript' 'JavaScript' ' JavaScript' 'JavaScript'
 ' Javascript' ' Javascript' ' JavaScript' 'JavaScript' ' Javascript'
 ' JavaScript' ' Javascript' ' JavaScript' ' Javascript' ' Javascript'
 'Javascript' ' JavaScript' ' JavaScript' 'JavaScript' ' JavaScript'
 ' JavaScript' ' JavaScript' 'JavaScript' ' Javascript' 'JavaScript'
 ' JavaScript' ' JavaScript' 'Javascript' ' JavaScript' 'JavaScript'
 ' JavaScript' ' Javascript' 'JavaScript' ' JavaScript' ' JavaScript'
 ' JavaScript' ' JavaScript' 'JavaScript' ' JavaScript' 'Javascript'
 'Javascript' 'JavaScript' ' JavaScript' ' JavaScript' ' JavaScript'
 ' JavaScript' ' JavaScript' ' JavaScript' 'JavaScript' ' JavaScript'
 ' JavaScript' ' JavaScript' ' JavaScript' ' Javascript' ' JavaScript'
 ' JavaScript' ' JavaScript' ' JavaScript' 'JavaScript' 'JavaScript'
 ' JavaScript' ' JavaScript' ' JavaScript' ' JavaScript' 'JavaScript'
 'JavaScript' ' JavaScript' 'JavaScript' ' JavaScript' ' JavaScript'
 ' JavaScript' ' JavaScript' ' ES2015 JavaScript' ' JavaScript']
['r' 'r' 'ceph' ..., ' Visual Basic' ' XML' ' Apex']
['aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws-lambda' 'aws' 'aws' 'aws' 'aws'
 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws'
 'aws' 'aws' 'aws' 'aws' 'aws' 'aws' 'aws-code-deploy' 'aws' ' AWS' ' AWS'
 'AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS stack' ' AWS'
 ' AWS' ' AWS' ' AWS' ' AWS' ' AWS SQS' ' AWS Kinesis' ' AWS RDS'
 ' AWS DynamoDB' ' AWS ElasticCache' ' AWS Redshift' ' AWS-Cloud' 'AWS'
 ' AWS' ' AWS stack' ' AWS' ' AWS' ' AWS' 'AWS Redshift' ' AWS' ' AWS'
 ' AWS' ' AWS EC2' ' AWS' ' AWS' ' AWS' ' AWS' 'AWS Services' ' AWS' ' AWS'
 ' AWS' ' AWS' ' AWS' 'AWS Services' ' AWS' ' AWS' 'AWS' ' AWS/Azure'
 ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS'
 ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS'
 ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS'
 ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS' ' AWS ELB' ' AWS' ' AWS' ' AWS'
 ' AWS']
['python' 'python' 'python' 'python' 'python' 'python' 'python' 'python'
 'python' 'python' 'python' 'python' 'python' 'python' 'python' 'python'
 'python' 'python' 'python' 'python' 'python' 'python' 'python' 'python'
 'python' 'python' 'python' 'python' 'python' 'python' 'python' 'python'
 'python' 'python' 'python' 'python' 'python' 'python' 'python' 'python'
 'python' 'python' 'Python' ' Python' ' Python' ' Python' ' Python'
 ' Python' ' Python' 'Python' ' Python Celery' ' Python' ' Python' 'Python'
 'Python' ' Python' 'Python' 'Python' ' Python' 'Python' ' Python'
 ' Python' ' Python' 'python' ' Python' ' Python' ' Python' ' Python'
 ' Python' ' Python' ' Python' ' Python' ' Python' ' Python' ' Python'
 'Python' ' Python' ' Python' 'Python' ' Python' 'Python' ' Python '
 ' Python' ' Python' ' Python' 'Python' 'Python' ' Python' ' Python'
 ' Python' ' Python' ' Python' ' Python' ' Python' ' Python' ' Python'
 ' Python' 'Python GUI' ' Python' ' Python' ' Python' ' Python' ' Python'
 ' Python' ' Python' 'Python' ' Python' ' Python' 'Python' ' Python'
 ' Python' ' Python' ' Python' 'Python' ' Python' ' Python' 'Python'
 'Python' ' Python' ' Python' ' Python' ' Python' 'Python' 'Python'
 ' Python' 'Python' 'Python' ' Python' ' Python' ' Python' 'Python'
 ' Python' ' Python' ' Python' ' Python' ' Python' ' Python' ' Python'
 ' Python' ' Python' ' Python' ' Python' ' Python' 'Python' ' Python'
 'Python' ' Python 3' ' Python' ' Python' ' Python' ' Python' ' Python'
 'Python' ' Python' ' Python' ' Python']
['ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby'
 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' 'ruby' ' Ruby' ' Ruby'
 ' Ruby' 'Ruby' ' Ruby' ' Ruby' ' Ruby' ' Ruby' 'Ruby w/o Rails' 'Ruby'
 'Ruby' ' Ruby' ' Ruby' ' Ruby' ' Ruby' ' Ruby' ' Ruby' 'Ruby' ' Ruby'
 ' Ruby' 'Ruby/RoR' ' Ruby ' ' Ruby' 'Ruby' ' Ruby' 'Ruby' 'Ruby' 'Ruby'
 ' Ruby' 'Ruby' ' Ruby' 'Ruby' 'Ruby' ' Ruby' ' Ruby' ' Ruby' ' Ruby'
 ' Ruby' 'Ruby' ' Ruby' ' Ruby' 'Ruby' ' Ruby' 'Ruby' 'Ruby' ' Ruby']
['rest' 'restful-web-services' 'rest' 'restful-architecture' 'rest' 'rest'
 'rest' 'rest' 'rest' 'rest' 'rest' ' Rest' ' REST' ' REST' ' REST/SOAP'
 ' Spring REST' ' REST' ' Rest' ' REST' ' Rest' ' REST' ' REST' 'REST'
 ' RESTful' ' REST' ' REST' ' REST' ' RESTful' ' REST' ' REST' ' Rest'
 ' REST' ' REST' ' Rest' ' REST' ' REST' ' REST' ' REST' ' RESTFul' ' REST'
 ' REST']
['sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql'
 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql' 'sql'
 'sql-server' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL'
 ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL'
 ' SQL' 'SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' ' SQL' 'SQL'
 ' Transact SQL' ' SQL' ' SQL' ' SQL' 'SQL' ' SQL' ' SQL' 'SQL' ' SQL'
 ' SQL Server' ' SQL' 'SQL' 'SQL' ' SQL' 'SQL' ' SQL' 'SQL' 'SQL'
 ' Cloud SQL' 'SQL' 'Sql' ' SQL' 'SQL' 'SQL' ' SQL' ' SQL' ' SQL' ' SQL'
 'SQL' ' SQL' ' SQL' ' SQL' ' SQL Injection']
['node.js' 'node.js' 'node.js' 'node.js' 'node.js' 'node.js' 'node.js'
 'node.js' 'node.js' 'node.js' 'node.js' 'node.js' 'node.js' 'node.js'
 'node.js' 'node.js' 'node.js' 'node.js' 'node.js' ' node.js' ' Node.js'
 ' Node.js' ' Node.js' ' Node.js' ' node.js' ' Node.js' ' Node.js'
 ' node.js' 'Node.js' ' node.js' 'Node.js' ' Node.js' ' Node.js' ' Node.js'
 ' Node.js' ' Node.js' 'Node.js CLI' ' Node.js' ' Node.js' ' node.js'
 ' Node.js' 'Node.js' ' Node.js' 'Node.js' ' Node.js' ' Node.js' ' Node.js'
 ' Node.js' ' Node.js' ' Node.js' ' Node.js']
['css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css'
 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css' 'css'
 'css' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' Post.css' ' CSS' ' CSS'
 ' CSS' 'CSS' 'CSS' ' CSS' ' modular CSS (SCSS' ' CSS' 'CSS' ' (S)CSS'
 ' CSS' ' CSS' ' (S)CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS'
 ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' (S)CSS' ' CSS' ' CSS'
 ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS/SCSS' ' CSS' ' CSS' ' CSS' ' CSS'
 ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS' ' CSS'
 ' CSS' ' CSS' ' CSS' ' SASS/CSS' ' SASS/CSS']
['html5' 'html5' 'html5' 'html5' 'html5' 'html5' 'html5' 'html5' 'html5'
 'html5' 'html5' 'html5' 'html5' 'html5' 'html5' 'html5' 'html5' 'html5'
 'html5' ' HTML5' ' HTML5' ' HTML5' ' HTML5' ' HTML5' 'HTML5' 'HTML5'
 'HTML5' ' HTML5' 'HTML5' ' HTML5' ' HTML5' ' HTML5' ' HTML5' ' HTML5'
 ' HTML5' 'HTML5' 'HTML5' ' HTML5' 'HTML5' ' HTML5' ' HTML5' ' HTML5'
 'HTML5' ' HTML5' ' HTML5' ' HTML5' ' HTML5' ' HTML5' 'HTML5' ' HTML5'
 ' HTML5' 'HTML5' ' HTML5' ' HTML5' 'HTML5' 'HTML5' ' HTML5' 'HTML5'
 'HTML5' ' HTML5' ' HTML5' ' HTML5' ' HTML5']
['php' 'php' 'php' 'php' 'php' 'php' 'php' 'php' 'php' 'php' 'php' 'php'
 'php' 'php' 'php' 'php' 'composer-php' 'php' 'php' 'php' 'php' 'php' 'php'
 'php' 'php' 'PHP' ' PHP' ' PHP' 'PHP' ' php-fpm' ' PHP' ' PHP' ' PHP'
 'PHP' ' PHP' ' PHP' ' PHP' 'PHP' 'PHP' ' PHP' ' PHP' 'OOP PHP' ' PHP'
 ' PHP' ' PHP' 'PHP' ' PHP' ' Behat (PHP)' ' PHP' 'PHP' ' PHP' 'PHP' ' PHP'
 'PHP' ' PHP' 'PHP' ' PHP' ' PHP' 'PHP' 'PHP' ' PHP' ' PHP' 'PHP' ' PHP'
 'PHP' ' PHP' ' PHP' 'PHP' ' PHP' 'PHP' ' PHP' 'PHP' ' PHP Codeception'
 'PHP' ' PHP' 'PHP' ' Phalcon PHP' ' PHP' ' PHP']
['java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java-ee'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java-ee'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java'
 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java' 'java'
 'java' 'java' 'java-ee' 'java' 'java' ' Java' 'Java' 'Java' ' Java'
 ' Java' 'Java' 'Java' ' Java' ' Java' ' Java' ' Java' ' Java' 'Java'
 ' Java' 'Java' 'Java' 'Java' ' Java' ' Java' ' Java' ' Java' 'Java'
 ' Java' ' Java' ' Java' ' JAVA' ' Java' 'Java' ' Java' ' Java' ' Java'
 'Java' ' Java' ' Java' ' Java' ' Java' 'Java' 'Java' ' Java' ' Java'
 ' Java' ' Java' ' Java' ' Java' ' Java' ' Java' ' Java' 'Java' 'Java'
 ' Java' ' Java' ' Java' ' Java' ' Java' ' Java' ' Java' ' Java' ' Java'
 'Java' ' Java' 'Java' 'Java' 'Java' 'Java' 'Java' 'Java' ' Java' ' Java'
 ' Java' 'Java' 'Java' 'Java' ' Java' 'Java' ' Java' 'Java']
['html' 'html' 'html' 'html' 'html' 'html' 'html' 'html' 'html' 'html'
 'html' 'html' 'html' ' HTML' 'HTML' ' HTML 5' 'HTML' 'HTML' 'HTML' ' HTML'
 ' HTML' ' HTML' ' HTML' 'HTML' 'HTML' ' HTML' 'HTML' 'HTML' ' HTML'
 ' HTML' ' HTML' ' HTML' 'HTML' ' HTML' ' HTML' 'HTML' 'HTML' ' HTML'
 ' HTML' ' HTML' ' HTML' 'HTML' ' HTML' ' HTML' ' HTML' ' HTML 5' ' HTML'
 '  HTML' 'HTML' ' HTML' ' HTML' 'HTML' ' HTML' ' HTML' ' HTML' ' HTML'
 ' HTML' ' HTML' ' HTML' 'HTML' ' HTML' ' HTML' 'HTML']
['ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails'
 'ruby-on-rails-4' 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails'
 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails'
 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails'
 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails' 'ruby-on-rails'
 'Ruby on Rails' ' Ruby on Rails' ' Ruby on Rails' ' Ruby on Rails'
 'Ruby on Rails' 'Ruby on Rails' 'Ruby-on-Rails' ' Ruby on Rails'
 'Ruby on Rails' 'Ruby on Rails' ' Ruby on Rails' ' Ruby on Rails'
 ' Ruby on Rails' 'Ruby on Rails' 'Ruby on Rails' ' Ruby on Rails'
 ' Ruby on Rails' ' Ruby on Rails' ' Ruby on Rails' 'Ruby on Rails'
 'Ruby on Rails' ' Ruby on Rails' ' Ruby on Rails' 'Ruby on Rails'
 'Ruby on Rails' 'Ruby on Rails' 'Ruby on Rails' 'Ruby on Rails'
 ' Ruby on Rails' ' Ruby on Rails']
['git' 'git' 'git' 'git' 'git' 'git' 'git' ' Git' ' git' 'Git' ' GIT'
 ' Git ' ' git' ' Git' ' Git' 'Git' ' Git' ' Git ' ' Git' ' Git' ' git'
 ' git' ' git' 'git' ' Git' ' git' ' GIT' ' git' ' git' ' git' ' Git'
 ' git' ' git' ' git' ' Git' ' GIT' ' Git' ' Git' ' Git' ' Git' ' Git'
 ' Git' ' Git' ' Git' ' GIT' ' Git' ' git' ' Git' ' git' '  Git' ' Git'
 ' Git' ' git' ' git' ' git' ' git' ' Git' ' Git' ' Git' ' GIT' ' Git'
 ' Git' ' Git' ' Git' ' Git' ' Git' ' Git' ' Git' ' Git' ' Git' ' Git'
 ' Git' ' Git' ' Git' ' Git VCS' 'Git' ' Git' ' Git' ' Git' ' Git' ' Git'
 ' Git']
['postgresql' 'postgresql' 'postgresql' 'postgresql' 'postgresql'
 'postgresql' 'postgresql' 'postgresql' 'postgresql' 'postgresql'
 'postgresql-9.6' 'postgresql' 'postgresql' 'postgresql' 'postgresql'
 ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' ' Postgresql' ' Postgresql' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' 'PostgreSQL' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' 'PostgreSQL' 'PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' 'PostgreSQL' ' PostgreSQL' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' ' Postgresql' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' 'PostgreSQL' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' ' PostgreSQL' ' PostgreSQL'
 ' PostgreSQL' ' PostgreSQL']
['mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql'
 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql'
 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' 'mysql' ' MySQL' ' MySQL'
 ' MySQL' ' MySQL' ' Mysql' ' MySQL' ' Mysql' ' MySQL' ' MySQL' 'mySQL'
 ' Mysql' ' MySQL' 'MySQL' ' MySQL' ' MYSQL' ' MySQL' ' MySQL' 'MySQL'
 ' Mysql' ' MySQL' ' MySQL' ' MySql' ' MySQL' ' MySQL' ' MySQL' ' MySQL'
 ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL'
 ' MySQL' ' MySQL' ' MySQL' ' MySQL ' ' MySQL' ' MySQL' ' MySQL' ' MySQL'
 ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL' ' MySQL'
 ' Mysql' ' MySQL' ' MySQL']
['jenkins' 'jenkins' 'jenkins' 'jenkins' 'jenkins' ' Jenkins' ' Jenkins'
 ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins'
 ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins'
 ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins'
 ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins'
 ' Jenkins' ' Jenkins' 'Jenkins' ' Jenkins ' ' Jenkins' ' Jenkins'
 ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins' ' Jenkins'
 ' Jenkins']
['react-redux' 'react' 'react-redux' ' React' ' React' ' React' ' React'
 ' React' ' React' ' React' ' React' ' React' ' React' ' React' ' react'
 ' React' ' React' ' React' ' React' ' React' ' React-router' ' React'
 ' React' ' React' ' React' ' React' ' React' ' React' ' React' ' React'
 ' React' ' React' ' React' ' React' ' React' ' React' ' React' ' React'
 ' React' ' React' ' React' ' React' ' React' ' React' ' React' ' React'
 ' React' 'React' ' React' ' React' ' React' 'React' ' React' ' React'
 ' React' ' React' 'React' ' React' ' React-router' ' React' ' React'
 ' React' ' React' ' React' ' React' ' React' ' React' ' React' ' React']
['linux' 'linux' 'linux' 'linux' 'linux' 'linux' 'linux' 'linux' 'linux'
 'linux' 'linux' 'linux' 'linux' 'linux' 'linux' 'linux' 'linux' ' Linux'
 ' Linux' ' Linux' ' Linux' ' Linux ' ' Linux' ' Linux' 'Linux' ' Linux'
 ' Linux' 'Linux' 'Linux' 'Linux' 'Linux' ' Linux' ' Linux' ' Linux'
 'Linux' ' Linux' 'Linux' ' Linux' ' Linux' 'Linux' ' Linux' 'Linux'
 'Linux' ' Linux' ' Linux' 'OSX/Linux' ' Linux' 'Linux' 'Linux' ' Linux'
 'Linux' ' Linux' ' Linux' ' Linux' 'Linux']
['nosql' 'nosql' 'nosql' 'nosql' 'nosql' 'nosql' 'nosql' 'nosql' 'nosql'
 ' NoSQL' ' nosql' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL'
 ' NoSQL' ' NoSQL' ' NoSQL' ' NoSql' ' NoSQL' ' NoSQL' ' NoSQL' 'NoSql'
 ' NoSql' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NOSQL' ' NOSQL' ' NoSQL'
 ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL' ' NoSQL'
 ' NoSQL' ' NoSQL' ' NoSQL']
['scala' 'scala' 'scala' 'scala' 'scala' 'scala' 'scala' 'scala' 'scala'
 'scala' 'scala' 'scala' 'scala' 'scala' 'scala' 'scala' 'scala' 'scala'
 'scala' 'scala' 'scala' 'scala' 'scala' ' Scala' ' Scala' 'Scala' ' Scala'
 ' Scala' 'Scala' 'Scala' ' Scala' ' Scala' 'Scala' 'Scala' 'Scala' 'Scala'
 'Scala' ' Scala' ' Scala' ' Scala' ' Scala' ' Scala' 'Scala' ' Scala'
 ' Scala' ' Scala' ' Scala' 'Scala' ' Scala' ' Scala' ' Scala' ' Scala'
 ' Scala' ' Scala' ' Scala' ' Scala' 'Scala' ' Scala' ' Scala']
['css3' 'css3' 'css3' 'css3' 'css3' 'css3' 'css3' ' CSS3 ' ' CSS3' ' CSS3'
 ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3'
 ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3'
 ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3' ' CSS3'
 ' CSS3' ' CSS3']
['scrum' 'scrum' 'scrum' 'scrum' 'scrum' 'scrum' 'scrum' 'scrum' 'scrum'
 'scrum' ' Scrum' 'Scrum' ' Scrum' ' Scrum' 'SCRUM' 'Scrum' ' SCRUM'
 ' scrum' ' SCRUM' ' Scrum' 'Scrum' ' Scrum' ' Scrum' 'Scrum' 'Scrum'
 ' Scrum' ' Scrum' ' Scrum' ' Scrum' 'SCRUM' ' Scrum' 'Scrum' ' Scrum'
 ' Scrum ' ' Scrum' ' Scrum' ' Scrum' ' Scrum' ' Scrum' ' Scrum' ' Scrum'
 ' Scrum' ' Scrum']
['video.js' 'backbone.js' 'backbone.js' 'backbone.js' 'JS' ' D3.js'
 'Angular.js' ' Backbone.js' ' Angular.js' ' Backbone.js'
 'JS Web Components' ' JS' ' Webpack/Require.js' ' Grunt.js ' ' Gulp.js '
 ' Require.js' ' Grunt.js' ' Gulp.js' ' Express.js' ' JS' ' nightwatch.js'
 ' next.js' ' JS' ' D3.js' ' Browser JS APIs' ' Ember.js' ' D3.js' ' d3.js'
 ' D3.js' ' Chart.js' 'Angular.js' ' Backbone.js' ' Backbone.js'
 ' Vanilla.js' ' Pixi.js' ' JS' ' Vanilla.js' ' Angular.js' ' Require.js'
 ' D3.js' ' Chart.js']
['elasticsearch' 'elasticsearch' 'elasticsearch' 'elasticsearch'
 ' ElasticSearch' ' Elasticsearch' ' Elasticsearch' 'ElasticSearch'
 ' Elasticsearch' ' Elasticsearch' ' Elasticsearch' ' Elasticsearch'
 ' Elasticsearch' ' Elasticsearch' ' Elasticsearch' ' ElasticSearch'
 ' ElasticSearch' ' Aerospike/Redis/Elasticsearch'
 ' Cassandra/ElasticSearch' ' ElasticSearch' ' ElasticSearch'
 ' Elasticsearch' ' ElasticSearch' ' Elasticsearch' ' ElasticSearch'
 ' ElasticSearch' ' Elasticsearch' ' Elasticsearch' ' Elasticsearch'
 ' Elasticsearch' 'ElasticSearch' 'ElasticSearch' ' ElasticSearch'
 ' ElasticSearch' ' ElasticSearch' ' ElasticSearch']
['docker' 'docker' 'docker' 'docker' 'docker' 'docker' 'docker' 'docker'
 'docker' 'docker' 'docker' 'docker' 'docker' 'docker' 'docker' 'docker'
 'docker' 'docker' 'docker' 'docker' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker' ' Kafka and Docker' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker' ' Docker' ' Docker Vagrant' ' Docker' ' Docker'
 ' Docker' ' Docker' 'Docker' ' Docker' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker' ' Docker' ' Docker' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker' ' Docker' ' Docker' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker' ' Docker' ' Docker' ' Docker-Compose' ' Docker'
 ' Docker' ' Docker' ' Docker' ' Docker Hub' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker' ' Docker' ' Docker' ' Docker' ' Docker' ' Docker'
 ' Docker' ' Docker']
['machine-learning' 'machine-learning' 'machine-learning'
 'machine-learning' 'machine-learning' ' Machine Learning'
 'Machine Learning' ' Machine Learning' ' Machine Learning'
 ' Machine Learning' ' Machine learning' ' Machine Learning'
 'Machine Learning' ' Machine Learning' ' Machine Learning'
 'Machine Learning' ' Machine Learning' ' Machine Learning']
[' Restful APIs' ' Rest APIs' ' RESTful API' ' REST API' 'REST API'
 'RESTful API' ' restful APIs' ' REST APIs' ' REST APIs' ' REST APIs'
 ' REST APIs' ' Restful API' ' REST API design' 'RESTful API'
 ' RESTful API' ' Restful APIs' ' REST API' ' REST APIs' 'RESTful API’s'
 'REST API’s' ' REST-APIs' ' REST API' ' REST API' ' REST APIs' ' REST API'
 ' RESTful API' ' RESTful API' ' RESTful APIs' ' RESTful APIs' ' REST APIs'
 ' RESTful APIs' ' RESTful APIs' ' REST APIs' ' REST APIs' ' RESTful-APIs'
 ' RESTful API' 'RESTful APIs' ' REST API' ' Restful APIs' ' REST APIs'

In [650]:
key=6
words = BagofWords(d[key])
print (len(d[key]))

85

In [651]:
len(d[7])

51

In [652]:
words

[('SQL', 59),
 ('sql', 25),
 ('server', 1),
 ('Transact', 1),
 ('Server', 1),
 ('Cloud', 1),
 ('Sql', 1),
 ('Injection', 1)]

In [653]:
skills.sort_values('cluster',ascending=False).to_csv("skills_features_cluster.tsv", encoding='utf8', index=False, sep='\t')

In [654]:
cluster_type={}

In [666]:
cluster_type[89] = 'JavaScript frameworks'
cluster_type[88] = 'Sass/LESS' #SASS
cluster_type[87] = 'React.js'
cluster_type[86] = 'scikit-learn / deep learning' 
cluster_type[85] = 'Unix/Linux'
cluster_type[84] = 'Spark' #apache-spark
cluster_type[83] = 'JavaScript frameworks' #vue.js
cluster_type[82] = 'JavaScript frameworks' #javascript es6
cluster_type[81] = 'api' 
cluster_type[80] = 'Unix/Linux' #unix
cluster_type[79] = 'NGINX'
cluster_type[78] = 'Node.js' #node
cluster_type[77] = 'React native'
cluster_type[76] = 'RabbitMQ'
cluster_type[75] = 'Cassandra'
cluster_type[74] = 'JavaScript frameworks' #es6
cluster_type[73] = 'Sass/LESS' #less
cluster_type[72] = 'Gulp'
cluster_type[71] = 'Continuous integration'
cluster_type[70] = 'Node.js' #NodeJS

In [667]:
cluster_type[69] = 'Django'
cluster_type[68] = 'CI/CD'
cluster_type[67] = 'TDD'
cluster_type[66] = 'Azure'
cluster_type[65] = 'Laravel'
cluster_type[64] = 'HTTP'
cluster_type[63] = 'Cloud'
cluster_type[62] = 'TypeScript'
cluster_type[61] = 'JSON'
cluster_type[60] = 'UI/UX'
cluster_type[59] = 'A/B Testing'
cluster_type[58] = 'Kafka'
cluster_type[57] = 'Redux'
cluster_type[56] = 'Apache Frameworks'
cluster_type[55] = 'Puppet'
cluster_type[54] = 'Chef'
cluster_type[53] = 'sysadmin'
cluster_type[52] = 'Google packages'
cluster_type[51] = 'JQuery'
cluster_type[50] = 'Sass/LESS' #sass

In [669]:
cluster_type[49] = 'Android'
cluster_type[48] = 'Ansible'
cluster_type[47] = 'Kubernetes'
cluster_type[46] = 'Hadoop'
cluster_type[45] = 'Kanban'
cluster_type[44] = 'iOS'
cluster_type[43] = 'Go'
cluster_type[42] = 'Swift'
cluster_type[41] = 'Agile' 
cluster_type[40] = 'Objective-C'
cluster_type[39] = 'Redis'
cluster_type[38] = 'Angular.js' #angular
cluster_type[37] = 'Selenium'
cluster_type[36] = 'Spring'
cluster_type[35] = ''
cluster_type[34] = 'Webpack'
cluster_type[33] = 'Angular.js' #angularjs
cluster_type[32] = 'Jira'
cluster_type[31] = 'Spark' #spark
cluster_type[30] = 'MongoDB'

In [658]:
cluster_type[29] = 'React.js' #reactjs
cluster_type[28] = 'RESTful APIs'
cluster_type[27] = 'Machine Learning'
cluster_type[26] = 'Docker'
cluster_type[25] = 'Elasticsearch' 
cluster_type[24] = 'JavaScript frameworks'
cluster_type[23] = 'Scrum' 
cluster_type[22] = 'CSS' #css3
cluster_type[21] = 'Scala'
cluster_type[20] = 'NoSQL'
cluster_type[19] = 'Unix/Linux' #linux
cluster_type[18] = 'React.js' #React
cluster_type[17] = 'Jenkins'
cluster_type[16] = 'MySQL'
cluster_type[15] = 'PostgreSQL'
cluster_type[14] = 'Git'
cluster_type[13] = 'Ruby' #ruby-on-rails #ruby on rails
cluster_type[12] = 'HTML'
cluster_type[11] = 'Java'
cluster_type[10] = 'PHP'

In [670]:
cluster_type[9] = 'HTML' #html5
cluster_type[8] = 'CSS' #css
cluster_type[7] = 'Node.js' #Node.js
cluster_type[6] = 'SQL'
cluster_type[5] = 'RESTful APIs' #REST
cluster_type[4] = 'Ruby'
cluster_type[3] = 'Python'
cluster_type[2] = 'AWS'
cluster_type[1] = 'mixed'
cluster_type[0] = 'JavaScript'

In [671]:
CT = pd.DataFrame.from_dict(cluster_type,orient='index')

In [672]:
CT = CT.reset_index()

In [673]:
CT.columns = ['cluster','type']

In [674]:
CT.keys()

Index(['cluster', 'type'], dtype='object')

In [675]:
skills.head()

   job_id   skill  cluster
0     553       r        1
1     553  python        3
2     553     sql        6
3     554  python        3
4     554     sql        6

In [676]:
skills_final = pd.merge(skills, CT, on='cluster')
skills_final = skills_final.drop('cluster', axis=1)
skills_final

      job_id                  skill                   type
0        553                      r                  mixed
1        554                      r                  mixed
2        556                   ceph                  mixed
3        557                     qa                  mixed
4        563               engineer                  mixed
5        563                backend                  mixed
6        566                    etl                  mixed
7        567                 devops                  mixed
8        567                   bash                  mixed
9        567             opennebula                  mixed
10       568                    etl                  mixed
11       568        amazon-redshift                  mixed
12       570                    c++                  mixed
13       572                 zeromq                  mixed
14       573        amazon-redshift                  mixed
15       573          amazon-lambda                  mixed
16       573         amazon-kinesis                  mixed
17       574                   hive                  mixed
18       574               dijkstra                  mixed
19       575                     c#                  mixed
20       575                   .net                  mixed
21       575           data-science                  mixed
22       576              websphere                  mixed
23       578          microservices                  mixed
24       579        user-experience                  mixed
25       580               mondrian                  mixed
26       583                routing                  mixed
27       583                  mesos                  mixed
28       584                    c++                  mixed
29       585                  c++14                  mixed
...      ...                    ...                    ...
4715     106            SASS / LESS              Sass/LESS
4716     142              Sass/Less              Sass/LESS
4717     166              LESS/SASS              Sass/LESS
4718     214              LESS/SASS              Sass/LESS
4719     338              Sass/LESS              Sass/LESS
4720     379              SASS/LESS              Sass/LESS
4721      94                 NodeJS                Node.js
4722     176                 NodeJS                Node.js
4723     212                 NodeJS                Node.js
4724     252                 NodeJS                Node.js
4725     277                 Nodejs                Node.js
4726     282                 NodeJs                Node.js
4727     290                 NodeJS                Node.js
4728     297                 NodeJS                Node.js
4729     375                 NodeJS                Node.js
4730     376                 Nodejs                Node.js
4731     379                 NodeJS                Node.js
4732     383                 NodeJS                Node.js
4733     402                 NodeJS                Node.js
4734     436                 NodeJS                Node.js
4735     466                 NodeJS                Node.js
4736     481                 NodeJS                Node.js
4737     142         JavaScript ES6  JavaScript frameworks
4738     151         Javascript ES6  JavaScript frameworks
4739     154  Javascript ES6/ES2015  JavaScript frameworks
4740     172         Javascript ES6  JavaScript frameworks
4741     379       JavaScript (ES6)  JavaScript frameworks
4742     383       JavaScript (ES6)  JavaScript frameworks
4743     392      JavaScript (ES6+)  JavaScript frameworks
4744     394       JavaScript (Es6)  JavaScript frameworks

[4745 rows x 3 columns]